Content Harvest
ucldc/rikolti pull request #335
Opened 2023-02-24 01:04 UTC by amywieliczka

Harvest Content Component

- `harvest_content/harvest_content_registry_collection.py` runs content harvester for registry endpoints with function `harvest_content_by_endpoint(url)`
- `harvest_content/lambda_shepherd.py` runs content harvester for a given collection with function `harvest_collection_content({"collection_id": 12345, "mapper_type": "mapper_name"}, None)`
- `harvest_content/lambda_function.py` runs content harvester for a given page with function `harvest_page_content({"collection_id": 12345, "mapper_type": "mapper_name", "page_filename": "1.jsonl"}, None)`

`harvest_page_content`: 
1) uses `get_mapped_records(collection_id, page_filename)` to read a file and return a list of records
2) creates an http client
3) uses `harvest_record_content(mapper_type, http_client, record, collection_id)` to run content harvester for a given record

`harvest_record_content`:
1) checks if we're harvesting nuxeo content, and if so, runs harvest_media, then gets children records, then runs harvest_record_content for each child
2) for all objects (nuxeo and non-nuxeo, parent and child), harvest_record_content runs harvest_thumbnail
3) harvest_record_content reports an error if there is no thumbnail, and a warning if there is no thumbnail but the object is an audio object. 

Derivatives Module defines:
- `make_thumbnail(source_file_path, mimetype)`
- `make jp2(source_file_path)`

Also defines `make_thumbnail` helpers:
- `make_thumb_from_pdf(pdf_file_path, thumb_file_path)`
- `make_thumb_from_video(video_path, thumb_path)`

2023-03-10 21:51 UTC, barbarahui commented on metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
> +                'url': url.replace('/nuxeo/', '/Nuxeo/'),
This line can be deleted.

2023-03-10 22:55 UTC, barbarahui requested changes
OK, I looked through it all on my own and it makes sense! Added a few inline comments/requests.

2023-03-10 22:55 UTC, barbarahui commented on content_harvester/by_page.py
> +        children_path = os.sep.join([local_path, 'children'])
Why not use `os.path.join` here? From my understanding after having read about `os.sep.join` vs `os.path.join`, the latter is more intelligent. You could end up with 2 separators in a row when using `os.sep.join`.

See https://docs.python.org/3/library/os.html?highlight=os%20sep#os.sep

2023-03-10 22:55 UTC, barbarahui commented on content_harvester/by_page.py
> +                child_page_path = os.sep.join([children_path, child_page])
Same question here re `os.sep.join`

2023-03-10 22:55 UTC, barbarahui commented on content_harvester/by_page.py
> +        if isinstance(thumbnail_src) == str:
Shouldn't this be `if isinstance(thumbnail_src, str)` ?

2023-03-10 22:55 UTC, barbarahui commented on content_harvester/by_page.py
> +        # but we have to use auth token to hit API endpoint
Yeah, hrm, I don't know if this is the case anymore since we upgraded Nuxeo and got rid of Shibboleth.

2023-03-10 22:55 UTC, barbarahui commented on content_harvester/derivatives.py
> +    return jp2_path
So much simpler! 👍

2023-03-14 08:34 UTC, amywieliczka commented on metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
> +                'url': url.replace('/nuxeo/', '/Nuxeo/'),
replaced `'url': url.replace('/nuxeo/', '/Nuxeo/')` with `'url': file_content.get('data', '').strip()` and removed line 203.

2023-03-28 20:22 UTC, barbarahui approved these changes

2023-03-28 21:26 UTC, merged