[WIP] Implement flk fetcher
ucldc/rikolti pull request #379
Opened 2023-03-29 23:57 UTC by lthurston

2023-03-31 18:30 UTC, lthurston commented
@timfrazee I'd love your feedback on this before I share with the CDL team.

2023-04-05 20:58 UTC, timfrazee commented on metadata_fetcher/fetchers/flk_fetcher.py
> +        return os.environ.get('FLICKR_API_KEY', 'boguskey')
For consistency, this should fetch the key from the settings module.

2023-04-06 17:54 UTC, lthurston commented
@amywieliczka @barbarahui This is ready for review. The one thing that I haven't thought too hard about is the change in `metadata_fetcher/lambda_function.py` to handle the change to the fetcher name. Let me know what you'd like me to do there.

2023-04-12 23:48 UTC, barbarahui requested changes
This method of making multiple requests for a page of fetched metadata looks good! We've made some comments inline. As a general principle, we're trying to avoid doing transformation of the vernacular metadata in the fetcher, so if you can rename `transform_vernacular_content()` to `aggregate_vernacular_content()` as per the comment, that would be great.

2023-04-12 23:48 UTC, barbarahui commented on metadata_fetcher/fetchers/flk_fetcher.py
> +            return self.get_photoset_request_url(self.harvest_extra_data,
Can you move the implementation of `self.get_photoset_request_url()` into this function instead of making it a separate function?

2023-04-12 23:48 UTC, barbarahui commented on metadata_fetcher/fetchers/flk_fetcher.py
> +        return self.get_user_photos_request_url(self.harvest_extra_data,
Can you move the implementation of `self.get_user_photos_request_url()` into this function instead of making it a separate function?

2023-04-12 23:48 UTC, barbarahui commented on metadata_fetcher/fetchers/flk_fetcher.py
> +        )
Can you change this to:
```
        print(
            f"[{self.collection_id}]: Fetched ids for page {self.write_page} "
            f"at {http_resp.url} with {self.photo_total} hits"
        )
```

2023-04-12 23:48 UTC, barbarahui commented on metadata_fetcher/fetchers/flk_fetcher.py
> +
Can you add:
```
        print(
            f"[{self.collection_id}]: Starting to fetch all photos for page"
            f" {self.write_page}"
        )
```

2023-04-14 21:41 UTC, lthurston commented on metadata_fetcher/lambda_function.py
> +        harvest_type = "flk"
I figured as much. I'm going to leave it for now so I can continue fetching, but will remove when we're ready to merge.

2023-04-14 22:48 UTC, lthurston commented
@barbarahui All changes have been made except the flickr -> flk change. Added retries too, although not in a particularly sophisticated way. Am happy to adjust however you see fit.

2023-04-26 17:36 UTC, amywieliczka submitted a review, later dismissed
Looks good!

Not sure what the overhead is for creating a new `requests.Session()` for fetching each object vs. having a single self.session that's created in in the `__init__` function and persists alongside the lifespan of the `FlkFetcher`. Might be worth looking into as a next step for retries - adding it as a card to the project board.

2023-04-26 17:36 UTC, barbarahui approved these changes

2023-04-27 21:25 UTC, lthurston commented on metadata_fetcher/lambda_function.py
> +        harvest_type = "flk"
@amywieliczka do you have a better solution than this workaround I have in place?

2023-04-27 21:28 UTC, lthurston commented
I pushed this branch again after rebasing on top of main. However, I think we're waiting until we have a solution for my little hack in the lambda_function, which is an unresolved conversation.

2023-04-28 21:31 UTC, lthurston commented on metadata_fetcher/lambda_function.py
> +        harvest_type = "flk"
This is resolved.

2023-05-01 15:32 UTC, lthurston commented
This PR is ready to be merged.

2023-05-02 20:44 UTC, barbarahui approved these changes

2023-05-03 20:59 UTC, merged