breaking: update local env variables FETCHER_DATA_DEST, MAPPER_DATA_DEST, and MAPPER_DATA_SRC
ucldc/rikolti pull request #495
Opened 2023-08-18 00:29 UTC by amywieliczka

2023-08-18 18:17 UTC, bibliotechy requested changes
@amywieliczka This works for me locally and all the changes looks good, so 👍 . 

But I think it is worth adding something to the README about what env vars to set so that someone just coming to this knows how that works? Also, should we have an `.env.example` or something similar to make that process easier / more explicit?

2023-08-18 18:24 UTC, bibliotechy commented
@amywieliczka @barbarahui  Not suggesting we go this route, but just tossing out the idea so it could be considered for future.

We could use a local [min.io](https://min.io/product/s3-compatibility) docker container as a stand in for s3. It has full s3 API compatibility and can be used [directly with the boto3](https://gist.github.com/heitorlessa/5b709df96ea6ac5ddc600545c0683d3b) library. If we ever run into a situation where the difference between s3 and local file storage starts adding too much complexity to the code or becomes a burden in some other way, this could be a path to consider

2023-08-18 18:37 UTC, bibliotechy commented
@amywieliczka actually, I hit an error on mapping, but I'm not sure if it is related to this change.

I set the ENV vars in `.env`

I successfully ran
```bash
python3 -m metadata_fetcher.fetch_registry_collections "https://registry.cdlib.org/api/v1/rikoltife
tcher/?format=json&mapper_type=tv_academy_oai_dc&ready_for_publication=true"
>>> Fetching 1/1 collections described at https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&mapper_type=tv_academy_oai_dc&ready_for_publication=true
Collection ID, Status, Total Pages, Rikolti Count, Solr Count, Diff Count, Solr Last Updated
1/1      : start fetching 27305 27305, success, 96, 953, 947, 6, 2022-11-23T12:42:50.760510
1/1      : finish fetching 27305
```
and I have the files stored locally.

But running the mapper for that collection failed with `Exception: ERROR: enrich_earliest_date not found in <class 'metadata_mapper.mappers.mapper.Record'>`. Full traceback below

```
$ python3 -m metadata_mapper.map_registry_collections "https://registry.cdlib.org/api/v1/rikoltimapper/?format=j
son&mapper_type=tv_academy_oai_dc&ready_for_publication=true"
>>> Mapping 1/1 collections described at https://registry.cdlib.org/api/v1/rikoltimapper/?format=json&mapper_type=tv_academy_oai_dc&ready_for_publication=true
Collection ID, Status, Extent, Solr Count, Diff Count, Message
1/1      : start mapping 27305 Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/map_registry_collections.py", line 106, in <module>
    map_endpoint(args.endpoint)
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/map_registry_collections.py", line 53, in map_endpoint
    map_result = lambda_shepherd.map_collection(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/lambda_shepherd.py", line 103, in map_collection
    mapped_page = map_page(json.dumps(payload), {})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/lambda_function.py", line 100, in map_page
    mapped_records = run_enrichments(
                     ^^^^^^^^^^^^^^^^
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/lambda_function.py", line 59, in run_enrichments
    enrichment_func, kwargs = parse_enrichment_url(enrichment_url)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/local-chnelson/projects/cdl/rikolti/metadata_mapper/lambda_function.py", line 52, in parse_enrichment_url
    raise Exception(f"ERROR: {enrichment_func} not found in {Record}")
Exception: ERROR: enrich_earliest_date not found in <class 'metadata_mapper.mappers.mapper.Record'>
```

2023-08-21 21:25 UTC, amywieliczka commented
Ahh, I'll add a .env.example - there is another environment variable for skipping undefined enrichments `export SKIP_UNDEFINED_ENRICHMENTS=True` Adding this should resolve the local mapping woes you describe.

2023-08-21 23:12 UTC, barbarahui approved these changes
I was able to fetch and map a collection using a local venv. Looks good to me. The only wrinkle of course is that as is, the `importlib.import_module` statements in `metadata_mapper/lambda_function.py` and `metadata_fetcher/lambda_function.py` fail when running in airflow. But I think we're trying to figure out what to do about that separately.

2023-08-22 20:26 UTC, barbarahui approved these changes

2023-08-23 18:57 UTC, bibliotechy approved these changes

2023-08-23 19:09 UTC, merged