Create single multi collection stg index
ucldc/rikolti pull request #918
Opened 2024-05-07 00:57 UTC by barbarahui

2024-05-07 22:18 UTC, amywieliczka commented on record_indexer/scripts/combine_individual_collection_stage_indices.py
> +        r.raise_for_status()
I recall opensearch provides really thorough details regarding why something has failed in the response text - I think instead, we want to add to the imports at the top: `from .utils import print_opensearch_error`, and then here:

```
    r = requests.post(url, headers=headers, data=json.dumps(data), auth=auth)
    if not (200 <= r.status_code <= 299):
        print_opensearch_error(r, url)
        r.raise_for_status()
```

2024-05-07 22:18 UTC, amywieliczka commented on record_indexer/scripts/combine_individual_collection_stage_indices.py
> +    auth = (os.environ.get("OPENSEARCH_USER"), os.environ.get("OPENSEARCH_PASS"))
I have, in my env.local

`RIKOLTI_ES_ENDPOINT`, `RIKOLTI_ES_USER`, and `RIKOLTI_ES_PASS`, I also see a `settings.get_auth()`

What are these `OPENSEARCH_` values supposed to be?

2024-05-07 22:18 UTC, amywieliczka commented on record_indexer/update_stage_index.py
> +    r.raise_for_status()
might want to add `print_opensearch_error` here.

2024-05-07 22:23 UTC, amywieliczka requested changes
I think you could probably just update these lines in the `create_stage_index_task` https://github.com/ucldc/rikolti/blob/02f813faa0461b8b72322a0a8ca059e7a00e5d61/dags/shared_tasks/indexing_tasks.py#L23-L28 to read:

```py
try:
    update_stage_index_for_collection(collection_id, version_pages)
except Exception as e:
    # TODO: implement some rollback exception handling?
    raise e
```

then you wouldn't have to make any changes to `harvest_dag.py`. 

If you're really set on creating a new `_task` function to match the `update_stage_index` function, then please do copy the log output and registry communication pieces from the `create_stage_index_task` function. 

These lines provide some handy log output for searching our opensearch index: https://github.com/ucldc/rikolti/blob/02f813faa0461b8b72322a0a8ca059e7a00e5d61/dags/shared_tasks/indexing_tasks.py#L31-L41

And this line tells the Collection Registry that the collection has been indexed successfully: https://github.com/ucldc/rikolti/blob/02f813faa0461b8b72322a0a8ca059e7a00e5d61/dags/shared_tasks/indexing_tasks.py#L43 - the second argument could simply be `{status: 'success'}` if you no longer think it makes sense to return the index name.

2024-05-09 17:49 UTC, barbarahui commented
I addressed Amy's review requests. Chad took a look and says all looks good. I'm going to go ahead and merge this into main without waiting for re-review from Amy since she's out sick.

2024-05-09 17:49 UTC, merged